# Generated by Django 5.2.1 on 2025-06-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='published_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Content_head0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Content_head1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Content_head2',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(default='', max_length=500),
        ),
    ]
