# Generated by Django 5.2.1 on 2025-06-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_published_date_blogpost_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='price',
        ),
    ]
