# Generated by Django 5.2.1 on 2025-06-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_update',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
